spring:
  datasource:
    url: jdbc:mysql://192.168.1.112:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    schema: classpath:/schema.sql

  application:
    name: auth-service
  redis:
    database: 0
    host: 192.168.1.112
    port: 6379

eureka:
  instance:
    health-check-url: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}
  client:
    serviceUrl:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@localhost:8761/eureka/

server:
  port: 5000
  context-path: /uaa
security:
  oauth2:
    resource:
      filter-order: 3


management:
  security:
    enabled: false
  context-path: /mgmt


