spring:
  application:
    name: webapp
server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}


security:
  user:
    name: user
    password: password
  oauth2:
    client:
      clientId: service-a
      clientSecret: ${security.user.password}
      accessTokenUri: http://localhost:8762/uaa/oauth/token
      grantType: client_credentials
      scope: server
    resource:
      user-info-uri: http://localhost:8762/uaa/current


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
          #这里将线程策略设置为SEMAPHORE
          strategy: SEMAPHORE