spring:
  rabbitmq:
    addresses: amqp://192.168.1.112:5672
    username: springcloud
    password: 123456
  application:
    name: consumer
  cloud:
    stream:
      bindings:
        input:
          destination: output
        output:
          destination: input
server:
  port: 8081