spring:
  application:
    name: publisher
  rabbitmq:
    addresses: amqp://192.168.1.112:5672
    username: springcloud
    password: 123456
  thymeleaf:
    cache: false
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  cloud:
    stream:
      bindings:
        input:
          destination: output
        output:
          destination: input
server:
  port: 8082
